(* ::Package:: *)

(* ::Input:: *)
(*(* :Title:BestExample*)*)
(*(* :Context:BestExample`*)*)
(*(* :Author:GS*)*)
(*(* :Summary:an example of good programming style*)*)
(*(* :Copyright:GS 2019*)*)
(*(* :Package Version:1*)*)
(*(* :Mathematica Version:12.1*)*)
(*(* :History:*)*)
(*(* :Keywords:programming style,local variables*)*)
(*(* :Sources:biblio*)*)
(*(* :Discussion:*)*)
(**)
(*BeginPackage["BubbleSortDSA`"]*)
(**)
(*(*PowerSum::usage="PowerSum[x, n] returns the sum of the first n powers of x."*)*)
(*NumberToCard::usage=""*)
(*CardToNumber::usage=""*)
(**)
(*Begin["Private`"]*)
(**)
(*cards = Import/@FileNames["Cards/*.png",NotebookDirectory[]];*)
(**)
(*(*Function to get value of a card*)*)
(*CardToNumber[c_]:= Module[{card = c},index = Part[Position[cards, c],1]-1; Part[Mod[index,10],1]]*)
(**)
(*(*Function to get a card with a certain value*)*)
(*NumberToCard[num_]:= Module[{number = num},color = RandomInteger[{0,3}]; Part[cards, num+1 + 10*color]]*)
(**)
(*(*Function to create a grid for the array*)*)
(*CreateArrayGrid[array_]:= Module[{a = array,i}, Table[Grid[{{Part[a, i]},{i }}, Frame-> All],{i,1,Length[a]}]]*)
(**)
(*(*Function to create a grid for the array with some elements highlighted in red*)*)
(*CreateArrayGrid[array_, highlight_]:= Module[{a = array,i, h = highlight, list}, *)
(*											h = Mod[h, Length[a]]; *)
(*											list =Table[Grid[{{Part[a, i]},{i}},Frame -> True, *)
(*												If[MemberQ[highlight, i] , FrameStyle->  Directive[Red,Thick], FrameStyle->  Directive[White, Thick]]],*)
(*												{i,1,Length[a]}];*)
(*											Grid[{list}]]*)
(**)
(*(*Function to compute the bubblesort frames with the associated comparisons*)*)
(*BubbleSortFrames[list_List]:=Module[{l=list,i,j,len=Length[list]},*)
(*								steps = List[list, list];*)
(*								comparisons = List[{}];*)
(*								Do[*)
(*								Do[*)
(*									If[CardToNumber[l[[j]]]> CardToNumber[l[[j+1]]],*)
(*											{l[[j]],l[[j+1]]}={l[[j+1]],l[[j]]},*)
(*											True];*)
(*									comparisons = Nest[Append[#, List[j, j+1]]&, comparisons,2]; *)
(*									steps = Nest[Append[#,l]&,steps,2],*)
(*										{j,1,len-1}];,*)
(*									{i,1,len-1}]; *)
(*								comparisons = Append[comparisons, List[{}]]; *)
(*								List[steps, comparisons]]*)
(**)
(*(*Function to create the bubblesort animation*)*)
(*BubbleSortAnimation[length_] := Module[{len = length, array, steps, comparisons},*)
(*									array = Table[NumberToCard[RandomInteger[9]],len];*)
(*									steps = Part[BubbleSortFrames[array],1];*)
(*									comparisons = Part[BubbleSortFrames[array],2];*)
(*									Animate[*)
(*										CreateArrayGrid[Part[steps,esecuzione], Part[comparisons, esecuzione]],*)
(*										{esecuzione,1,Length[steps],1}, *)
(*										ControlPlacement->Top, DefaultDuration -> Length[steps]]]*)
(**)
(*Swap[array_, i_, j_] := ReplacePart[array, {i+1-> array[[j+1]], j+1-> array[[i+1]]}];*)
(*dim = 10;*)
(*(*originalArray=Table[Part[cards,RandomInteger[40]], dim];*)*)
(*originalArray=Table[NumberToCard[RandomInteger[9]], dim];*)
(*currentArray = originalArray;*)
(*arrayDisplay= CreateArrayGrid[currentArray];*)
(*Dynamic[TogglerBar[Dynamic[selection],arrayDisplay]]*)
(*Button["Scambia", Dynamic[If[Length[selection]== 2, *)
(*							currentArray = Swap[currentArray, Part[selection, 1,1,2,1], Part[selection, 2,1,2,1]];*)
(*							selection = List[];*)
(*							arrayDisplay= CreateArrayGrid[currentArray, dim],*)
(*							selection = List[]]]]*)
(**)
(*End[]*)
(**)
(*EndPackage[]*)


(* ::Input:: *)
(**)


(* ::Input:: *)
(**)
