(* ::Package:: *)

(* ::Input:: *)
(*(* :Title:BestExample*)*)
(*(* :Context:BestExample`*)*)
(*(* :Author:GS*)*)
(*(* :Summary:an example of good programming style*)*)
(*(* :Copyright:GS 2019*)*)
(*(* :Package Version:1*)*)
(*(* :Mathematica Version:12.1*)*)
(*(* :History:*)*)
(*(* :Keywords:programming style,local variables*)*)
(*(* :Sources:biblio*)*)
(*(* :Discussion:*)*)
(**)
(*BeginPackage["BubbleSortDSA`"]*)
(**)
(*PowerSum::usage="PowerSum[x, n] returns the sum of the first n powers of x."*)
(**)
(*Begin["Private`"]*)
(**)
(*PowerSum[x_,n_]:=Module[{i},Sum[x^i,{i,1,n}]]*)
(**)
(*End[]*)
(**)
(*EndPackage[]*)


(* ::Input:: *)
(**)


(* ::Input:: *)
(**)
